### ISSUE TITLE
Unable to extract zookeeper-3.5.5.tar.gz in Windows

### ISSUE THREAD

**Issue by ignatovich-artem** [lean-delivery/ansible-role-zookeeper#15]
##### SUMMARY

Unable to extract zookeeper-3.5.5.tar.gz in Windows with ansible without errors.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Unarchive to temporary directory
##### ANSIBLE VERSION

```
2.7.12
```
##### OS / ENVIRONMENT

Windows
##### STEPS TO REPRODUCE

```yaml
  - name: Unarchive to temporary directory
    win_unzip:
      src: '{{ zk_tarball_dir }}/zookeeper-{{ zk_version }}.tar.gz'
      dest: '{{ temp_dir_path }}'
      recurse: true
```

##### ACTUAL RESULTS

```
    fatal: [test-aws-Windows2019-zookeeper-3-5-tgz]: FAILED! => changed=false 
      dest: System.Collections.Hashtable
      msg: 'Error recursively expanding ''C:\Users\molecule\AppData\Local\Temp/zookeeper-3.5.5.tar.gz'' to ''System.Collections.Hashtable''! Msg: Access to the path ''C:\Users\molecule\System.Collections.Hashtable\apache-zookeeper-3.5.5-bin\docs\apidocs\zookeeper-jute\org\apache\zookeeper\server\persistence\class'' is denied.'
      pscx_status: present
      removed: false
      src: C:\Users\molecule\AppData\Local\Temp/zookeeper-3.5.5.tar.gz

```
